### ISSUE TITLE
Error message after check for new version.

### ISSUE THREAD

**Issue by sercxjo** [RingOV/gis-weather#22]
Gis Weather 0.8.0
Папка конфигурации:
    /home/sergio/.config/gis-weather/gw_config1.json
Размеры виджета:
    ширина = 684 высота = 320 в т.ч. отступ = 20
Скриншот сохранен в /home/sergio/.config/gis-weather/main_screenshot.png
Ваш экран не поддерживает прозрачность
> Получаю погоду на 7 дней
> Скачиваю http://www.gismeteo.ru/city/weekly/4992
OK
> обновлено на сервере 21:00
> погода получена 00:03
> Следующее обновление через 30 мин
----------------------------------------
> Проверяю наличие новой версии (deb)
Traceback (most recent call last):
  File "/usr/share/gis-weather/gis-weather.py", line 704, in redraw
    check_updates()
  File "/usr/share/gis-weather/gis-weather.py", line 462, in check_updates
    if diff_versions.diff(v.split('.'), new_ver):
  File "/usr/share/gis-weather/utils/diff_versions.py", line 7, in diff
    new_ver = fix_digits(new_ver)
  File "/usr/share/gis-weather/utils/diff_versions.py", line 21, in fix_digits
    if len(i) < 2:
TypeError: object of type 'int' has no len()

**Comment by RingOV** [comment]
эта проблема уже исправлена, но когда выйдет 0.8.1 придется обновляться в ручную.

В любое время можно собрать себе deb из самой последней git-версии.

  - build git version
    - `sudo apt-get install git fakeroot`
    - First build `cd && git clone https://github.com/RingOV/gis-weather.git && cd gis-weather/scripts && python3 build_deb.py && cd ../DEB && sudo dpkg -i *.deb`
    - or (after First build) `cd && cd gis-weather && git pull https://github.com/RingOV/gis-weather.git && cd scripts && python3 build_deb.py && cd ../DEB && sudo dpkg -i *.deb`

**Comment by sercxjo** [comment]
При установке через dpkg `/usr/bin/gis-weather` оказывается неисполняемым.
Нужно делать `sudo chmod +x /usr/bin/gis-weather`

**Comment by RingOV** [comment]
https://github.com/RingOV/gis-weather/blob/master/scripts/build_deb.py#L66
при сборке это и делается, но почему-то срабатывает не на всех машинах.

**Comment by RingOV** [comment]
А если так? Собирается с исполняемым?
0.8.0.40
fix exec permissions 2 https://github.com/RingOV/gis-weather/commit/df6f4f03b3fcaa5cff87b41e8c2ee4d82be4251e

**Comment by sercxjo** [comment]
Ничего не изменилось. fakeroot вообще имеет смысл делать для всего скрипта сразу, потому что он хранит в ОЗУ изменения прав доступа.

А почему не сделать сборку через debian/rules, как положено в debian?

**Comment by RingOV** [comment]
/home монтируется с noexec?

Я не против debian/rules, и не откажусь от помощи.

**Comment by sercxjo** [comment]
Раздел ext4 смонтирован без noexec. Вставил ls -l сразу после chmod - видимо dpkg-deb сбрасывает биты обратно.
