### ISSUE TITLE
Accuweather does not work in degrees F setting.

### ISSUE THREAD

**Issue by j75080** [RingOV/gis-weather#24]
When trying to view my weather using Accuweather in the Fahrenheit setting for temperature units, gis-weather 0.8.1 fails with the following lines from the command line:

Traceback (most recent call last):
  File "/usr/share/gis-weather/gis-weather.py", line 775, in expose
    weather1 = get_weather()
  File "/usr/share/gis-weather/gis-weather.py", line 436, in get_weather
    return data.get_weather(service)
  File "/usr/share/gis-weather/services/data.py", line 78, in get_weather
    return accuweather.get_weather()
  File "/usr/share/gis-weather/services/accuweather.py", line 486, in get_weather
    t_f[0][0] = F_to_C(t_f[0][0])
TypeError: 'tuple' object does not support item assignment
> Check for new version (deb)
> You are using the latest version
----------------------------------------

Gis-weather using Accuweather works when I change the temperature units to Celsius.

**Comment by RingOV** [comment]
Try 0.8.1.1 version with fixes 82cc02cc3c080987933924384c39850e73aee350

**Comment by j75080** [comment]
This corrects the issue.

Thank you,
j75080
