### ISSUE TITLE
Gis-weather 0.8.2.5 stop working!

### ISSUE THREAD

**Issue by ilianiron** [RingOV/gis-weather#35]
Installed on kubuntu 18.04 and worked with no problems 3 weeks, but from 3 days after starting hangs with getting weather....not responded to nothing! The only way to stop is killing process!

**Comment by RingOV** [comment]
https://github.com/RingOV/gis-weather/issues/34

open ~/.config/gis-weather/gw_config1.json
and manually edit to "service": "Gismeteo",

**Comment by ilianiron** [comment]
Doesn't work this thread- open ~/.config/gis-weather/gw_config1.json
and manually edit to "service": "Gismeteo"! Gave me "invalid data".
City codes for accuweather, gismeteo has changed! Yr.no only work but the temperature data is wrong! Open weather has problem with code and API-keys and so they not work!
 May be need new version with new code! 1,5 years has not new version-this is very long time!

**Comment by lega99** [comment]
gis-weather stopped working yesterday afternoon, no meteorological site is operational. He does not work for Manjaro, Calculate-Gentoo, Neon 16.04, Kubuntu 18.04.  My setup was already Gismeteo. the program multiplies gw_config1.json to gw_config2.json, gw_config3.json

**Comment by ilianiron** [comment]
Openweathermap data and forecast is incorrect! Simply remove gis-weather and wait for new corrected version!

**Comment by kooshball** [comment]
Getting error "Unable to download page, check the network connection" with Openweathermap.  My internet connection is fine as I am able to come to this page able to hit https://openweathermap.org/city/5199600 with chrome.

**Comment by kooshball** [comment]
Getting the following error when I switch from Celsius to Fahrenheit:
Traceback (most recent call last):
  File "/usr/share/gis-weather/gis-weather.py", line 876, in expose
    self.Draw_Weather(self.cr)
  File "/usr/share/gis-weather/gis-weather.py", line 1002, in Draw_Weather
    self.draw_weather_icon_now(cr, 0, 20 + margin)
  File "/usr/share/gis-weather/gis-weather.py", line 1208, in draw_weather_icon_now
    self.draw_text(cr, t_today[i].split(';')[t_index], x0+a*((j+1)//2), y0+11+b*(i//2), font+' Normal', 8, 50,Pango.Alignment.LEFT)
IndexError: list index out of range

The version of the app is 0.8.2.65-1 with the Yr weather service.  Unable to use other services due to the errors listed in the previous comments.

**Comment by RingOV** [comment]
**ilianiron**, your right.
**kooshball**, send me e-mail with all output of openweather getting weather.

**Comment by lega99** [comment]
openweathermap working, api key and city codes. In some periods they do not have data for today
Gismeteo and other metheological sites have the same code on the web page, but it seems that the procedure for obtaining data has changed

**Comment by vlag24** [comment]
well, it's working for me on MxLinux i686 (32bits) version 0.8.2.5 right now with openweather. I used to use accuweather but as you know it's not working anymore since a few days so I delete the conf version and start the app again (which create a new conf file) and everything works great chosing openweather.
![2018-05-20_11 23](https://user-images.githubusercontent.com/6505894/40277526-bc6bbe46-5c0f-11e8-950b-6b6b7fa1aaad.png)

**Comment by RingOV** [comment]
**lega99**, OpenWeather not have data for today, then this period of time in past.

**Comment by lega99** [comment]
RingOV,
I'm completely confused, I have a KDEplasmoid that feeds data with yr.no and meteorological data agree with data with openweather: pressure, temperature, wind speed 
![screenshot_20180520_130527](https://user-images.githubusercontent.com/39432815/40279242-8ca7ba74-5c2e-11e8-949e-24b9e456e8d4.png)

**Comment by lega99** [comment]
RingOV,
My mistake, this is the meteorological forecast and the openweather and yr.no does not show the past time. In any case, I install Meteo forecast with a meteorological alarm

**Comment by yuranos** [comment]
Will gismeteo integration be fixed anywhere soon? Does it make any sense to wait or should we switch to OpenWeatherMap?

**Comment by yuranos** [comment]
OpenWeatherMap doesn't work for me. Says "Invalid location code".

**Comment by lega99** [comment]
If you have the correct API key?, the location code has not been changed

**Comment by yuranos** [comment]
Hi, @lega99.
Well, I registered and copy-pasted it from their web site just today. I will check it one more time, but in any case it's confusing.

**Comment by yuranos** [comment]
Hi @lega99.
Apologies, I think I just needed to wait a bit longer before the key was being activated. Now I'm able to add a location, but the widget is still not showing any data.

**Comment by lega99** [comment]
Hi, yuranos
I used the API key from another program. Yesterday I reinstalled gis-weather and I used this API key from another program and to the city code from all over the page. City codes were not changed, the procedure for sending data to the program may be changed, only openweather works according to the old procedure. It may be a problem with the python version 2.x or 3.x...

**Comment by RingOV** [comment]
OpenWeather problem I understand. 
https://openweathermap.org/price
Free API not alowed 16 daily weather, but it worked before.
I need time for edit getting weather from 5 days/3 hour forecast API.

**Comment by lega99** [comment]
If I understand your writing well, this means that there is a problem in meteorological servers that charge their services. Free services are very limited so it becomes difficult to write a program that will cover all options because yr.no has its policy what it gives or does not give for free, the accuweather does not seem to give anything more free, Gismeteo also. Plus all these meteorological servers have a target group of windows users and billing services. I have Accuweather on my mobile phone and the service is free, so I will not know how to stay.

**Comment by protegh** [comment]
Today I noticed the following: When gis-weather stalls (trying to get data from Accuweather) or fails on start (ImportError: No module named 'gi'. I use Gentoo Linux and my self made Ebuild was buggy.) it changed the config in `~/.config/gis-weather/`) and on the next start I get
`... (normal start messages)
> Herunterladen https://www.gismeteo.com/city/weekly/14135
OK
Traceback (most recent call last):
  File "/usr/share/gis-weather/gis-weather.py", line 722, in redraw
    self.expose_indicator()
  File "/usr/share/gis-weather/gis-weather.py", line 733, in expose_indicator
    weather1 = get_weather()
  File "/usr/share/gis-weather/gis-weather.py", line 442, in get_weather
    return data.get_weather(service)
  File "/usr/share/gis-weather/services/data.py", line 76, in get_weather
    return gismeteo.get_weather()
  File "/usr/share/gis-weather/services/gismeteo.py", line 268, in get_weather
    city_name = re.findall('type[A-Z].*\">(.*)<', w_now[0])
IndexError: list index out of range
`
and here it stalls again. With an old working config from backup or a complete new config gis-weather with gismeteo works again.

**Comment by lega99** [comment]
@protegh
Which languages for forecast are offered in the set .  I have only Russian and 3 former Russian republics

**Comment by protegh** [comment]
@lega99
For Gismeteo I have English, Russian, 3 former Russian republics, Romana. I have localized on English.

**Comment by lega99** [comment]
@protegh 
Thanks for your reply. I have English too, but if you choose an English option in setting the weather forecast location, the program does not accept it. I chose Russian to set up forecast locations and then the program accepts my location New Belgrade in Serbia.
Definitely the program must be completely changed if the author wants it.. As far as I could look at the web pages, all the weather forecasts are given in 5 days

**Comment by RingOV** [comment]
OpenWeatherMap working now with free api key.
Use 5 days / 3 hour weather.
Added sunrise, sunset, sun_duration.
Added new preset for OpenWeatherMap.
Need testing.

**Comment by arvana** [comment]
You have a bug in openweathermap.py line 187:

json.dump(source, open('/home/ringov/weather.json', "w", encoding='utf-8')

Most of us don't have a home folder called ringov. ;)

**Comment by RingOV** [comment]
**arvana**, thank you
Fixed ebb3631bf86b58053b79885a40a37e27f9fcdd41

**Comment by lega99** [comment]
[url=https://postimg.cc/image/nn5whmjm3/][img]https://s33.postimg.cc/nn5whmjm3/023.png[/img][/url]

**Comment by RingOV** [comment]
**lega99**, https://github.com/RingOV/gis-weather/issues/35#issuecomment-393295058

> Added new preset for OpenWeatherMap.

**Comment by lega99** [comment]
Thanks for the effort but I'm not a developer. I compile the git version you put on the directions you gave
https://github.com/RingOV/gis-weather
I'm doing my last night's link and the result is the one in the picture, plus I had to type API key

**Comment by RingOV** [comment]
**lega99**, https://github.com/RingOV/gis-weather/issues/35#issuecomment-393295058

> Added new preset for OpenWeatherMap.

mean
![menu](https://user-images.githubusercontent.com/3176489/40957641-b331d77a-689e-11e8-9802-4ff25e9f6de1.png)

**Comment by lega99** [comment]
@RingOV 
Thank you for the explanation. I did not think I'd go to that menu. I have set openweathermap at the city, API key is a requirement and I expected the program to set the mask for the display for 5 days. Programming and intervention was my job, my mistake, the difrent logic. It was always easier for me to write the program again than to rectify the program with the change of essential starting points

**Comment by lega99** [comment]
[url=https://postimg.cc/image/uc5linn3v/][img]https://s33.postimg.cc/4gluzgla7/103.png[/img][/url]

**Comment by lega99** [comment]
@RingOV,
<a href='https://postimages.org/' target='_blank'><img src='https://s33.postimg.cc/tvyml8kkf/2dana.png' border='0' alt='2dana'/></a>

There are not two days in the prognosis. This is a situation I have already shown before the program is changed.

**Comment by phd21** [comment]
Hi RingOV,

I have been using this wonderful weather application for years until recently.

BUT for months now, I cannot get any weather service to work with this application anymore? What is going on with this software? Is there going to be an update to fix this, or is there a simple way to fix this? I am using Linux Mint 17.x (Ubuntu 14.04) and 18.x (Ubuntu 16.04).

Regards,
Phil (phd21)
phd21mint@gmail.com

**Comment by jeffkny** [comment]
Hello. As with other users, I am getting error on startup with Gis-weather, and with any weather service. I went so far as to get an API for openWeatherMap, and still getting error "Error getting data". This is a sad occurrence for me, as I have used this app quite awhile. I love it on my desktop (Mint 18). Hoping it can be repaired soon.
Jeff in USA

**Comment by opuntia41** [comment]
My Gis-weather stopped working. I think it may have to do with the Linux kernel. I accepted kernel updates and afterwards Gis stopped working. It would load on start-up but would report an error. I don't have a fix for this.

**Comment by wtrabbithole** [comment]
Widget stopped getting weather from Gismeteo site. There may be a problem with the changed page code on the site

**Comment by lega99** [comment]
Gismeteo change free forecast to 3 days
https://www.gismeteo.com/

**Comment by RingOV** [comment]
Try lastest version.

**Comment by alideda** [comment]
@RingOV 

What version, where
